version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    command: uvicorn leadsy_api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
  db:
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./scripts/create-test-database.sql:/docker-entrypoint-initdb.d/10-create-test-database.sql
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - 5432:5432
volumes:
  postgres-data:
