"""Add password reset tokens table

Revision ID: 57e664cd16f5
Revises: 6d72f913dab2
Create Date: 2023-08-14 09:52:19.478369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e664cd16f5'
down_revision = '6d72f913dab2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
