"""Add password reset tokens table

Revision ID: a3de8755d4d5
Revises: 57e664cd16f5
Create Date: 2023-08-14 10:15:44.567662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3de8755d4d5'
down_revision = '57e664cd16f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
